security:

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: null

            # activate different ways to authenticate

            http_basic: ~
            # https://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: null
            # https://symfony.com/doc/current/cookbook/security/form_login_setup.html

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
